#!/usr/bin/env python3
"""
Build a formatted PDF for the Winter 2026 Tree-Ring report.
Requires: pip install fpdf2
"""
from __future__ import annotations

import sys
from pathlib import Path
from typing import Optional

try:
    from fpdf import FPDF
except ImportError:
    print("Install fpdf2: pip install fpdf2", file=sys.stderr)
    sys.exit(1)

REPO = Path(__file__).resolve().parents[1]
RESULTS = REPO / "results"
OUT_DEFAULT = REPO / "results" / "Winter2026_TreeRing_Report.pdf"


def img_path(name: str) -> Optional[Path]:
    p = RESULTS / name
    if not p.exists():
        return None
    return p


class ReportPDF(FPDF):
    def __init__(self) -> None:
        super().__init__(format="letter", unit="mm")
        self.set_auto_page_break(auto=True, margin=20)
        self.set_margins(22, 22, 22)

    def title_page(self) -> None:
        self.add_page()
        self.set_font("Helvetica", "B", 20)
        self.multi_cell(0, 10, "Tree-Ring Watermarking for Diffusion Images", align="C")
        self.ln(4)
        self.set_font("Helvetica", "", 12)
        self.multi_cell(0, 6, "Winter 2026 - Course report (Feiyang Xu)", align="C")
        self.ln(16)
        self.set_font("Helvetica", "I", 11)
        self.multi_cell(
            0,
            5,
            "Reproduction and evaluation of the Tree-Ring method (Wen et al., arXiv:2305.20030) "
            "with Stable Diffusion 1.5, including robustness to attacks and JPEG-focused "
            "detector variants.",
            align="C",
        )

    def h1(self, text: str) -> None:
        self.ln(6)
        self.set_font("Helvetica", "B", 14)
        self.multi_cell(0, 7, text)
        self.ln(2)

    def h2(self, text: str) -> None:
        self.ln(4)
        self.set_font("Helvetica", "B", 12)
        self.multi_cell(0, 6, text)
        self.ln(1)

    def body(self, text: str) -> None:
        self.set_font("Helvetica", "", 11)
        self.multi_cell(0, 5, text)
        self.ln(2)

    def caption(self, text: str) -> None:
        self.set_font("Helvetica", "I", 9)
        self.set_text_color(60, 60, 60)
        self.multi_cell(0, 4, text)
        self.set_text_color(0, 0, 0)
        self.ln(3)

    def add_figure(self, path: Optional[Path], caption: str, max_w_mm: float = 170.0) -> None:
        if path is None or not path.is_file():
            self.set_font("Helvetica", "I", 9)
            self.multi_cell(0, 4, f"[Missing image: {caption}]")
            self.ln(2)
            return
        self.add_page()
        try:
            self.image(str(path), x=22, w=max_w_mm)
        except Exception as e:  # noqa: BLE001
            self.set_font("Helvetica", "I", 9)
            self.multi_cell(0, 4, f"[Could not embed image: {e}]")
        self.ln(2)
        self.caption(caption)


def build_pdf(out: Path) -> None:
    pdf = ReportPDF()
    pdf.title_page()

    pdf.add_page()
    pdf.h1("Abstract")
    pdf.body(
        "This report summarizes the paper reading and experiments I completed during the "
        "Winter 2026 term. The project is based on the Tree-Ring watermarking method proposed by "
        "Wen et al. in Tree-Ring Watermarks: Fingerprints for Diffusion Images that are Invisible "
        "and Robust. The experiments compared clean and watermarked images under several attacks, "
        "including cropping, rotation, blurring, and JPEG compression. The baseline detector worked "
        "well when there was no attack, but JPEG compression at quality 25 made detection much "
        "harder. To improve JPEG robustness, I tested different detector-side approaches, including "
        "averaging across latent channels and selecting the minimum distance across channels. I also "
        "varied the Fourier mask radius and swept JPEG quality levels, as detailed in the experiments "
        "log (experiments/jpeg_defense/ATTEMPTS.md). The results showed that mean aggregation did not "
        "improve performance, while the min-distance approach gave a relatively strong improvement "
        "under JPEG compression. Overall, the research shows that Tree-Ring watermarking can be "
        "effective, but robustness under strong compression is still an important challenge."
    )

    pdf.h1("1. Introduction")
    pdf.body(
        "Diffusion models can generate realistic images from text prompts. As these models become "
        "more common, it is important to develop methods that can identify whether an image was "
        "generated by AI. One solution is watermarking, where a hidden signal is embedded into the "
        "image generation process. A good watermark should be invisible to human viewers but still "
        "detectable by an algorithm after the image has been edited or compressed."
    )
    pdf.body(
        "This report focuses on the Tree-Ring watermarking method. Instead of adding a visible mark "
        "to the final image, the Tree-Ring method embeds a hidden fingerprint into the initial noise "
        "used by the diffusion model. Since diffusion models generate images by gradually denoising "
        "this initial noise, the watermark can be carried through the generation process into the final "
        "image."
    )
    pdf.body(
        "The main purpose of this project was to reproduce the Tree-Ring pipeline using Stable "
        "Diffusion 1.5 and evaluate how robust the watermark is under different attacks. The "
        "experiments used fifty watermarked images and fifty clean images for each attack setting. "
        "The detector performance was measured using ROC curves, AUC, true positive rate at fixed "
        "false positive rates, and best accuracy. Figures 1 and 2 show the baseline detector results. "
        "The clean and watermarked images are clearly separated when there is no attack, but the "
        "separation becomes weaker under stronger distortions. JPEG compression at quality 25 is "
        "especially damaging because it causes more overlap between clean and watermarked detection "
        "scores."
    )

    pdf.add_figure(
        img_path("tree_ring_sd_n50_distances.png"),
        "Figure 1. Empirical distributions of the Tree-Ring detection distance for watermarked and "
        "clean images under different attacks.",
    )
    pdf.add_figure(
        img_path("tree_ring_sd_n50_roc.png"),
        "Figure 2. ROC curves for detecting watermarked images under different attacks.",
    )

    pdf.h1("2. Background")
    pdf.body(
        "Diffusion models generate images by starting from random noise and gradually removing noise "
        "through many denoising steps. Since the final image depends on the initial noise, the initial "
        "latent noise is used to hide a watermark."
    )
    pdf.body(
        "The Tree-Ring method does not require training or fine-tuning the diffusion model. Before "
        "image generation begins, a secret key is embedded into selected Fourier coefficients of the "
        "initial noise. These coefficients are chosen using a fixed circular mask in the frequency "
        "domain. The remaining coefficients are left as normal Gaussian noise, so the generated image "
        "still appears natural."
    )
    pdf.body(
        "This project used Stable Diffusion 1.5. Stable Diffusion does not generate directly in RGB "
        "pixel space. Instead, it uses a VAE latent space. For a typical 512x512 image, the latent "
        "representation has shape 4x64x64. The four channels are learned latent channels, not red, green, "
        "and blue image channels. To detect the watermark, the image is first encoded back into the VAE "
        "latent space. Then, DDIM inversion is used to estimate the original initial noise. A "
        "two-dimensional Fourier transform is applied to the inverted latent, and the Fourier "
        "coefficients inside the watermark mask are compared with the secret key. If the distance "
        "between the recovered coefficients and the key is small, the image is more likely to be "
        "watermarked."
    )

    pdf.h1("3. Experimental setup")
    pdf.body(
        "The experiments used Stable Diffusion 1.5 with the Tree-Ring watermarking method. For each "
        "attack, I tested fifty watermarked images and fifty clean images. The same detection method "
        "was applied to both groups."
    )
    pdf.body(
        "The evaluated attacks included: no attack; crop with ratio 0.75; rotation by 75 degrees; "
        "JPEG compression at quality 25; blur with strength 8. Other attacks in the full snapshot "
        "include color jitter and additive noise. The main evaluation metrics were: AUC; TPR at 1% FPR; "
        "TPR at 5% FPR; best accuracy (optimal threshold). JPEG compression at quality 25 was the "
        "most important attack to study further because it caused the baseline detector to perform "
        "much worse."
    )

    pdf.h1("4. Detector approaches for JPEG robustness")
    pdf.body(
        "The baseline JPEG detector used only the first latent channel after DDIM inversion. It also "
        "used a fixed Fourier mask radius and key scale 1.0. In the later experiments, the embedding "
        "process and model weights stayed the same. Only the detection method was changed. This made "
        "the comparison more controlled because any performance change came from the detector rather "
        "than from retraining or changing the image generation process."
    )

    pdf.h2("4.1 Mean aggregation across channels")
    pdf.body(
        "The first approach was to average the four VAE latent channels at each spatial location. After "
        "averaging, one two-dimensional Fourier transform was applied, and the same Tree-Ring distance "
        "was computed. The reason for trying this method was that averaging might reduce noise from "
        "imperfect DDIM inversion. If JPEG compression affects different channels in slightly different "
        "ways, averaging could potentially keep the shared watermark signal while reducing random channel "
        "noise. However, the results did not show a clear improvement. On the JPEG Q25 test with a sample "
        "size of 50, the AUC stayed close to the baseline. The baseline AUC was about 0.75, while mean "
        "aggregation gave about 0.749. Best accuracy only increased slightly from about 0.69 to about "
        "0.70. More importantly, the performance at strict false positive rates became worse. TPR at "
        "1% FPR decreased from about 0.10 to about 0.06, and TPR at 5% FPR decreased from about 0.30 to "
        "about 0.10. This means that mean aggregation is not a good fix for JPEG compression, "
        "especially when the detector needs to avoid false positives."
    )

    pdf.h2("4.2 Min-distance across channels")
    pdf.body(
        "The second approach was to compute the Tree-Ring distance separately for each of the four "
        "latent channels. Then, instead of averaging the channels, the detector selected the smallest "
        "distance as the final image-level score. The idea behind this method is that JPEG compression "
        "and inversion errors may not affect all latent channels equally. One channel may still preserve "
        "the watermark more clearly than the others. By choosing the channel with the smallest distance "
        "to the key, the detector may recover a stronger watermark signal. This method performed much "
        "better in the JPEG experiments. With a larger mask radius, such as r=12, the min-distance "
        "detector achieved about 0.90 AUC, 0.26 TPR at 1% FPR, 0.58 TPR at 5% FPR, and 0.85 best "
        "accuracy. This is a large improvement compared with the JPEG baseline, which had about 0.75 "
        "AUC and 0.69 best accuracy. However, this method also needs careful interpretation. Since it "
        "chooses the best result out of four channels, the false positive rate and p-values may need "
        "extra calibration. Future work should test this method on a larger clean validation set."
    )

    pdf.h2("4.3 Additional ablations")
    pdf.body(
        "I also tested other changes, including different Fourier mask radii (for example, comparing "
        "r=8, 10, and 12 with mean and min-distance rules), larger key scales in some runs, and a sweep "
        "over different JPEG quality values. A preliminary mean-channel radius ablation at n=20 "
        "suggested that r=8 and r=12 could outperform the default r=10 on some metrics; a full n=50 "
        "min-distance radius run gave about 0.89 AUC at r=8 and about 0.90 AUC at r=10 and r=12. The "
        "min-distance quality sweep (multiple Q and radii) is summarized in the repository log (see "
        "experiments/jpeg_defense/ATTEMPTS.md). These experiments show that JPEG Q25 is only one point "
        "on a larger compression robustness curve."
    )
    pdf.add_figure(
        img_path("jpeg_approaches_table.png"),
        "Figure 3. JPEG robustness comparison across detector settings and Fourier mask radii (curated).",
    )

    pdf.h1("5. Results")
    pdf.h2("5.1 Multi-attack robustness")
    pdf.add_figure(
        img_path("montage_sample0_all_attacks.png"),
        "Figure 4. Montage of one watermarked sample under different attacks.",
    )
    pdf.body("Table 1 shows the main quantitative results from results/metrics_snapshot_n50.md.")
    pdf.ln(2)
    # Simple table
    col_w = 32
    pdf.set_font("Helvetica", "B", 9)
    headers = ("Attack", "AUC", "TPR@1%", "TPR@5%", "Best acc.")
    for i, h in enumerate(headers):
        pdf.cell(col_w, 6, h, border=1, align="C")
    pdf.ln()
    rows = [
        ("none", "0.97", "0.70", "0.88", "0.94"),
        ("crop (0.75)", "0.89", "0.14", "0.36", "0.83"),
        ("rot. (75 deg)", "0.85", "0.12", "0.36", "0.78"),
        ("JPEG (Q25)", "0.75", "0.10", "0.30", "0.69"),
        ("blur (8)", "0.72", "0.28", "0.28", "0.75"),
    ]
    pdf.set_font("Helvetica", "", 9)
    for row in rows:
        for c in row:
            pdf.cell(col_w, 5, c, border=1, align="C")
        pdf.ln()
    pdf.caption("Table 1. Snapshot metrics (n=50) from results/metrics_snapshot_n50.md (excerpt).")
    pdf.body(
        "The no-attack case had the best performance, with an AUC of 0.97 and best accuracy of 0.94. "
        "Cropping and rotation reduced performance but still kept moderate separability between clean "
        "and watermarked images. JPEG Q25 caused a larger drop, with AUC decreasing to 0.75 and best "
        "accuracy decreasing to 0.69. Blur also reduced performance, with an AUC of 0.72."
    )

    pdf.h2("5.2 JPEG compression results")
    pdf.body(
        "The JPEG Q25 baseline used only the first latent channel, with mask radius r=10, key scale "
        "1.0, and n=50. The baseline achieved about 0.75 AUC, 0.10 TPR at 1% FPR, 0.30 TPR at 5% FPR, "
        "and 0.69 best accuracy. Mean aggregation across channels did not meaningfully improve the "
        "result. Although the best accuracy increased slightly to about 0.70, the true positive rate at "
        "strict false positive rates became worse. The min-distance detector gave the best JPEG "
        "performance. With a larger mask radius such as r=12, it reached about 0.90 AUC and 0.85 best "
        "accuracy. This suggests that at least one latent channel may keep the watermark signal more "
        "strongly after JPEG compression."
    )
    pdf.add_figure(
        img_path("jpeg_report_summary.png"),
        "Figure 5. Curated one-page summary of the JPEG robustness experiments.",
    )
    pdf.add_figure(
        img_path("jpeg_quality_sweep.png"),
        "Figure 6. JPEG quality sweep: detection performance vs. compression level.",
    )

    pdf.h1("6. Conclusion")
    pdf.body(
        "This project reproduced and evaluated the Tree-Ring watermarking method for "
        "diffusion-generated images using Stable Diffusion 1.5. The baseline detector worked well when "
        "there was no attack and remained somewhat robust under cropping and rotation. However, JPEG "
        "compression significantly reduced detection performance. To improve JPEG robustness, I tested "
        "mean aggregation and min-distance detection across latent channels, and I varied mask radius "
        "and quality as documented in experiments/jpeg_defense/ATTEMPTS.md. Mean aggregation did not "
        "improve the result and hurt performance at strict false positive rates. The min-distance "
        "detector across channels gave a much stronger improvement, especially when combined with a "
        "larger Fourier mask radius. Overall, the experiments suggest that Tree-Ring watermarking is a "
        "promising method for detecting diffusion-generated images, but JPEG robustness remains a key "
        "challenge. Future work should use larger evaluation sets, calibrate multi-channel detectors "
        "carefully, and explore watermark designs that are more robust to compression."
    )

    pdf.h1("Citation")
    pdf.set_font("Helvetica", "", 11)
    pdf.multi_cell(
        0,
        5,
        "Wen, Y., Kirchenbauer, J., Geiping, J., & Goldstein, T. Tree-Ring Watermarks: Fingerprints for "
        "Diffusion Images that are Invisible and Robust. arXiv:2305.20030.",
    )

    out.parent.mkdir(parents=True, exist_ok=True)
    pdf.output(str(out))
    print(f"Wrote {out}")


if __name__ == "__main__":
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else OUT_DEFAULT
    build_pdf(out)
